### PR TITLE
Handle one term messages, large messages and LITERALs in messages

### PR DESCRIPTION
**Pull request by gregjohnsonsaltaire**
* handle one term messages eg Request.search(["ALL"]) on an empty mailbox returns "* SEARCH\r\n"
* handle large messages, eg response from SEARCH ALL on a mailbox with 500+ messages
* handle LITERALs in message bodies (ie {size}\r\n<content>) eg FETCH "BODY[HEADER.FIELDS (RECEIVED)]"

### CODE REVIEW

**Comment by cosmin-harangus** [comment]
Thanks Greg for the PR... I will review and try to fix the issue with the travis check before merging.

**Comment by gregjohnsonsaltaire** [comment]
Hi Cosmin,

Thanks …

I only found Elixir a few months ago and am on the wrong side of 65 so please, please don’t hesitate to refactor.

Many thanks again for Eximap …

Regards,
Greg

**Comment by gregjohnsonsaltaire** [comment]
Hi Cosmin,

The Travis issue is probably because the PR is configured with an IMAP password of “admin” as per the documentation:

"curl --insecure --request POST --url https://localhost/admin/install/server --form install[hostname]=127.0.0.1 --form install[superAdmin]=admin@127.0.0.1 --form install[superAdminPassword]=admin”

compared with:
"The credentials used in testing this library are: Host: localhost.dev Port: 993 User: admin@localhost.dev <mailto:admin@localhost.dev> Pass: secret”

Happy to fix if you let me know your preferred process …

Regards,
Greg Johnson

**Comment by cosmin-harangus** [comment]
Thanks Greg for the tip. I've fixed the travis build and the PR works now. I've merged it in master and will update the hex.pm package.

**Pull request merged**
